name = "maho-solver"
main = "src/index.ts"
compatibility_date = "2024-03-29"
compatibility_flags = ["nodejs_compat"]

account_id = "CLOUDFLARE_ACCOUNT_ID"
workers_dev = true # or zone_id = "<ZONE ID>" if you have one

[vars]
SOLVER_KEY = ""

